//this source code was auto-generated by tolua#, do not modify it
using System;
using UnityEngine;

namespace LuaInterface.BaseType.ObjectWrap
{

public class ToLua_Gen_Initer_Register__
{
	public static void Init(LuaState L)
	{
		L.BeginModule(null);

		L.BeginModule("System");
		System_ArrayWrap.Register(L);
		L.BeginModule("Collections");

		L.BeginModule("Generic");
		System_Collections_Generic_ListWrap.Register(L);

		L.EndModule();//Generic
		L.EndModule();//Collections
		L.EndModule();//end System
	}

	public ToLua_Gen_Initer_Register__()
	{
		LuaState.AddIniter(Init);
	}
} //end class ToLua_Gen_Initer_Register__
} //end namespace LuaInterface.ObjectWrap
namespace LuaInterface
{
public partial class ObjectTranslator
{
	static LuaInterface.BaseType.ObjectWrap.ToLua_Gen_Initer_Register__ s_gen_reg_dumb_obj_basetype = new LuaInterface.BaseType.ObjectWrap.ToLua_Gen_Initer_Register__();
	static LuaInterface.BaseType.ObjectWrap.ToLua_Gen_Initer_Register__ gen_reg_dumb_obj_basetype {get{return s_gen_reg_dumb_obj_basetype;}}
} //end class ObjectTranslator
} //end namespace LuaInterface
