//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ToLuaGameFramework_LuaConfigWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ToLuaGameFramework.LuaConfig), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", new LuaCSFunction(op_Equality));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("UseLuaBundle", new LuaCSFunction(get_UseLuaBundle), null);
		L.RegVar("UseResBundle", new LuaCSFunction(get_UseResBundle), null);
		L.RegVar("LuaDevPath", new LuaCSFunction(get_LuaDevPath), null);
		L.RegVar("OutputPath_Android", new LuaCSFunction(get_OutputPath_Android), null);
		L.RegVar("OutputPath_IOS", new LuaCSFunction(get_OutputPath_IOS), null);
		L.RegVar("OutputPath_PC", new LuaCSFunction(get_OutputPath_PC), null);
		L.RegVar("RemoteUrl", new LuaCSFunction(get_RemoteUrl), null);
		L.RegVar("ExportLuaPaths", new LuaCSFunction(get_ExportLuaPaths), new LuaCSFunction(set_ExportLuaPaths));
		L.RegVar("ExportRes_For_Startup", new LuaCSFunction(get_ExportRes_For_Startup), new LuaCSFunction(set_ExportRes_For_Startup));
		L.RegVar("ExportRes_For_Delay", new LuaCSFunction(get_ExportRes_For_Delay), new LuaCSFunction(set_ExportRes_For_Delay));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UseLuaBundle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, ToLuaGameFramework.LuaConfig.UseLuaBundle);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UseResBundle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, ToLuaGameFramework.LuaConfig.UseResBundle);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaDevPath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.LuaDevPath);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutputPath_Android(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.OutputPath_Android);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutputPath_IOS(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.OutputPath_IOS);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutputPath_PC(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.OutputPath_PC);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RemoteUrl(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ToLuaGameFramework.LuaConfig.RemoteUrl);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExportLuaPaths(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ToLuaGameFramework.LuaConfig.ExportLuaPaths);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExportRes_For_Startup(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, ToLuaGameFramework.LuaConfig.ExportRes_For_Startup);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExportRes_For_Delay(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, ToLuaGameFramework.LuaConfig.ExportRes_For_Delay);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ExportLuaPaths(IntPtr L)
	{
		try
		{
			string[] arg0 = ToLua.CheckStringArray(L, 2);
			ToLuaGameFramework.LuaConfig.ExportLuaPaths = arg0;
			ToLuaGameFramework.LuaConfig.ExportLuaPaths = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ExportRes_For_Startup(IntPtr L)
	{
		try
		{
			System.Collections.Generic.Dictionary<string,string> arg0 = (System.Collections.Generic.Dictionary<string,string>)ToLua.CheckObject(L, 2, TypeTraits<System.Collections.Generic.Dictionary<string,string>>.type);
			ToLuaGameFramework.LuaConfig.ExportRes_For_Startup = arg0;
			ToLuaGameFramework.LuaConfig.ExportRes_For_Startup = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ExportRes_For_Delay(IntPtr L)
	{
		try
		{
			System.Collections.Generic.Dictionary<string,string> arg0 = (System.Collections.Generic.Dictionary<string,string>)ToLua.CheckObject(L, 2, TypeTraits<System.Collections.Generic.Dictionary<string,string>>.type);
			ToLuaGameFramework.LuaConfig.ExportRes_For_Delay = arg0;
			ToLuaGameFramework.LuaConfig.ExportRes_For_Delay = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

