//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Cricket_Game_GameArchWrapWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Cricket.Game.GameArchWrap), typeof(System.Object));
		L.RegFunction("GetArchitecture", new LuaCSFunction(GetArchitecture));
		L.RegFunction("GetMsgDispatcher", new LuaCSFunction(GetMsgDispatcher));
		L.RegFunction("GetNetManager", new LuaCSFunction(GetNetManager));
		L.RegFunction("GetMsgSender", new LuaCSFunction(GetMsgSender));
		L.RegFunction("New", new LuaCSFunction(_CreateCricket_Game_GameArchWrap));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCricket_Game_GameArchWrap(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Cricket.Game.GameArchWrap obj = new Cricket.Game.GameArchWrap();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Cricket.Game.GameArchWrap.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetArchitecture(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			QFramework.IArchitecture o = Cricket.Game.GameArchWrap.GetArchitecture();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMsgDispatcher(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Cricket.Common.IMsgDispatcher<byte[]> o = Cricket.Game.GameArchWrap.GetMsgDispatcher();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNetManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Cricket.Common.INetManager<byte[]> o = Cricket.Game.GameArchWrap.GetNetManager();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMsgSender(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Cricket.Common.IMsgSender<byte[],byte[]> o = Cricket.Game.GameArchWrap.GetMsgSender();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

