//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Cricket_Game_MsgSenderPBWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Cricket.Game.MsgSenderPB), typeof(System.Object));
		L.RegFunction("SendMessage", new LuaCSFunction(SendMessage));
		L.RegFunction("OnCallback", new LuaCSFunction(OnCallback));
		L.RegFunction("New", new LuaCSFunction(_CreateCricket_Game_MsgSenderPB));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("NetManager", new LuaCSFunction(get_NetManager), new LuaCSFunction(set_NetManager));
		L.RegVar("MsgDispatcher", new LuaCSFunction(get_MsgDispatcher), new LuaCSFunction(set_MsgDispatcher));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCricket_Game_MsgSenderPB(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Cricket.Game.MsgSenderPB obj = new Cricket.Game.MsgSenderPB();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Cricket.Game.MsgSenderPB.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendMessage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				Cricket.Game.MsgSenderPB obj = (Cricket.Game.MsgSenderPB)ToLua.CheckObject<Cricket.Game.MsgSenderPB>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte[] arg1 = ToLua.CheckByteBuffer(L, 3);
				obj.SendMessage(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				Cricket.Game.MsgSenderPB obj = (Cricket.Game.MsgSenderPB)ToLua.CheckObject<Cricket.Game.MsgSenderPB>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte[] arg1 = ToLua.CheckByteBuffer(L, 3);
				System.Action<bool,int> arg2 = (System.Action<bool,int>)ToLua.CheckDelegate<System.Action<bool,int>>(L, 4);
				obj.SendMessage(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Cricket.Game.MsgSenderPB.SendMessage");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Cricket.Game.MsgSenderPB obj = (Cricket.Game.MsgSenderPB)ToLua.CheckObject<Cricket.Game.MsgSenderPB>(L, 1);
			uint arg0 = (uint)LuaDLL.luaL_checkinteger(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			int arg2 = (int)LuaDLL.luaL_checkinteger(L, 4);
			obj.OnCallback(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NetManager(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Cricket.Game.MsgSenderPB obj = (Cricket.Game.MsgSenderPB)o;
			Cricket.Common.INetManager<byte[]> ret = obj.NetManager;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index NetManager on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MsgDispatcher(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Cricket.Game.MsgSenderPB obj = (Cricket.Game.MsgSenderPB)o;
			Cricket.Common.IMsgDispatcher<byte[]> ret = obj.MsgDispatcher;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MsgDispatcher on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_NetManager(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Cricket.Game.MsgSenderPB obj = (Cricket.Game.MsgSenderPB)o;
			Cricket.Common.INetManager<byte[]> arg0 = (Cricket.Common.INetManager<byte[]>)ToLua.CheckObject<Cricket.Common.INetManager<byte[]>>(L, 2);
			obj.NetManager = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index NetManager on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MsgDispatcher(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Cricket.Game.MsgSenderPB obj = (Cricket.Game.MsgSenderPB)o;
			Cricket.Common.IMsgDispatcher<byte[]> arg0 = (Cricket.Common.IMsgDispatcher<byte[]>)ToLua.CheckObject<Cricket.Common.IMsgDispatcher<byte[]>>(L, 2);
			obj.MsgDispatcher = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MsgDispatcher on a nil value");
		}
	}
}

