//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Cricket_Game_AppConstWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Cricket.Game.AppConst), typeof(System.Object));
		L.RegFunction("New", new LuaCSFunction(_CreateCricket_Game_AppConst));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("ipaddress", new LuaCSFunction(get_ipaddress), new LuaCSFunction(set_ipaddress));
		L.RegVar("port", new LuaCSFunction(get_port), new LuaCSFunction(set_port));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCricket_Game_AppConst(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Cricket.Game.AppConst obj = new Cricket.Game.AppConst();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Cricket.Game.AppConst.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ipaddress(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Cricket.Game.AppConst.ipaddress);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_port(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, Cricket.Game.AppConst.port);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ipaddress(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			Cricket.Game.AppConst.ipaddress = arg0;
			Cricket.Game.AppConst.ipaddress = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_port(IntPtr L)
	{
		try
		{
			ushort arg0 = (ushort)LuaDLL.luaL_checkinteger(L, 2);
			Cricket.Game.AppConst.port = arg0;
			Cricket.Game.AppConst.port = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

