//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Cricket_Game_MsgDispatcherPBWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Cricket.Game.MsgDispatcherPB), typeof(System.Object));
		L.RegFunction("Register", new LuaCSFunction(_Register));
		L.RegFunction("UnRegister", new LuaCSFunction(UnRegister));
		L.RegFunction("Dispatcher", new LuaCSFunction(Dispatcher));
		L.RegFunction("New", new LuaCSFunction(_CreateCricket_Game_MsgDispatcherPB));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCricket_Game_MsgDispatcherPB(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Cricket.Game.MsgDispatcherPB obj = new Cricket.Game.MsgDispatcherPB();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Cricket.Game.MsgDispatcherPB.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _Register(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Cricket.Game.MsgDispatcherPB obj = (Cricket.Game.MsgDispatcherPB)ToLua.CheckObject<Cricket.Game.MsgDispatcherPB>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			System.Action<byte[]> arg1 = (System.Action<byte[]>)ToLua.CheckDelegate<System.Action<byte[]>>(L, 3);
			obj.Register(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegister(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Cricket.Game.MsgDispatcherPB obj = (Cricket.Game.MsgDispatcherPB)ToLua.CheckObject<Cricket.Game.MsgDispatcherPB>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			System.Action<byte[]> arg1 = (System.Action<byte[]>)ToLua.CheckDelegate<System.Action<byte[]>>(L, 3);
			obj.UnRegister(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispatcher(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Cricket.Game.MsgDispatcherPB obj = (Cricket.Game.MsgDispatcherPB)ToLua.CheckObject<Cricket.Game.MsgDispatcherPB>(L, 1);
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			obj.Dispatcher(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

